language: sh
os: linux
arch: amd64
dist: bionic
sudo: required

services:
    - docker

script: 
    - chmod +x keypad-app/travis-packaging.sh
    - sh keypad-app/travis-packaging.sh

before_deploy:
    - git config --local user.name "Dominik Soukup"
    - git config --local user.email "soukupdo@gmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG

deploy:
    provider: releases
    file: /home/travis/build/soukudom/web-buttons/keypad-app/iox-web-aarch64/package.tar
    skip_cleanup: true
    token: $GITHUB_TOKEN
    overwrite: true
    on:
        tags: false
#        branch: master

notifications:
    email: false
