language: sh
os: linux
arch: amd64
dist: bionic
sudo: required

services:
    - docker

script: 
    - chmod +x keypad-app/travis-packaging.sh
    - sh keypad-app/travis-packaging.sh

deploy:
    provider: releases
    file: /home/travis/build/soukudom/web-buttons/keypad-app/iox-web-aarch64/package.tar
    skip_cleanup: true
    token: $GITHUB_TOKEN
    overwrite: true
#    on:
#        tags: true
#        branch: master

notifications:
    email: false
